### ISSUE TITLE
API tries to resolve removed shows

### ISSUE THREAD

**Issue by danielkoster** [danielkoster/argosd#45]
If you request the /episodes API endpoint, and an episode is present who has it's show deleted, the API will throw an exception.

```
Exception on /episodes [GET]
Traceback (most recent call last):
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/peewee.py", line 3090, in get
    return next(clone.execute())
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/peewee.py", line 2267, in next
    obj = self.iterate()
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/peewee.py", line 2249, in iterate
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/argosd/argosd/api/common/authentication.py", line 28, in decorated
    return function(*args, **kwargs)
  File "/opt/argosd/argosd/api/resources/episodes.py", line 15, in get
    return [episode.to_dict() for episode in episodes]
  File "/opt/argosd/argosd/api/resources/episodes.py", line 15, in <listcomp>
    return [episode.to_dict() for episode in episodes]
  File "/opt/argosd/argosd/models.py", line 61, in to_dict
    Episode.created_at, Episode.link])
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/playhouse/shortcuts.py", line 115, in model_to_dict
    rel_obj = getattr(model, field.name)
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/peewee.py", line 1309, in __get__
    return self.get_object_or_id(instance)
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/peewee.py", line 1300, in get_object_or_id
    obj = self.rel_model.get(self.field.to_field == rel_id)
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/peewee.py", line 4787, in get
    return sq.get()
  File "/opt/argosd/.virtualenv/lib/python3.5/site-packages/peewee.py", line 3094, in get
    % self.sql())
argosd.models.ShowDoesNotExist: Instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."title", "t1"."follow_from_season", "t1"."follow_from_episode", "t1"."minimum_quality", "t1"."wait_minutes_for_better_quality" FROM "show" AS t1 WHERE ("t1"."id" = ?)
PARAMS: [6]
```

**Comment by danielkoster** [comment]
Fixed in release v1.3.0.
